project_id = "jtfbocwsfxwrzfzvzgja"

[functions.import-full-listening-test]
verify_jwt = false

[functions.evaluate-speaking-submission]
verify_jwt = true

[functions.evaluate-writing-submission]
verify_jwt = true

[functions.set-user-gemini-api-key]
verify_jwt = true

[functions.explain-answer]
verify_jwt = false

[functions.analyze-performance]
verify_jwt = true

[functions.translate-word]
verify_jwt = false

[functions.generate-listening-audio]
verify_jwt = true

[functions.transcribe-listening-audio]
verify_jwt = false

[functions.import-listening-audio]
verify_jwt = false

[functions.analyze-listening-audio]
verify_jwt = true

[functions.admin-listening-action]
verify_jwt = false

[functions.generate-ai-practice]
verify_jwt = true
